#!/usr/bin/env bash

# User Configs
age_out_days=1
age_out_count=20

echo ""
echo "░█████╗░████████╗███████╗███████╗"
echo "██╔══██╗╚══██╔══╝██╔════╝██╔════╝"
echo "██║░░╚═╝░░░██║░░░█████╗░░█████╗░░"
echo "██║░░██╗░░░██║░░░██╔══╝░░██╔══╝░░"
echo "╚█████╔╝░░░██║░░░███████╗███████╗"
echo "░╚════╝░░░░╚═╝░░░╚══════╝╚══════╝"
echo ""
echo "［ＲＥＣ］"
echo ""

if [ "$(id -u)" = "0" ]; then
    echo "[x] This script should not be started with with SUDO but will request it for a few subcommands.." >&2
    exit 1
fi

# Set Current Directory as Starting Directory
starting_dir=$(pwd)

set -e # Exit on error

# Define directory to save output files
output_dir=$HOME/.ctee/
script_dir=$(dirname "$0")

# Handle optional argument for log filename
log_filename=${1:-"ctee_log_$(date +%Y%m%d%H%M%S)"}
db_filename="$log_filename.db"
echo "[i] Output Logfile: $starting_dir/$log_filename"

# Function to cleanup temp files and remove pid file
function cleanup {
  echo ""
  echo "    [i] Cleaning up..."
  rm -f "$temp_bashrc"
  rm -f "$output_dir/ctee.pid" # remove pid file when script ends

  # Remove files older than 7 days
  find "$output_dir" -name "cli_record_*" -mtime +$age_out_days -exec rm {} \;
  find "$output_dir" -name "cli_timer_*" -mtime +$age_out_days -exec rm {} \;

  # If there are more than 'age_out_count' files, delete the oldest
  (ls -f -t1 $output_dir"cli_record_"* 2>/dev/null | head -n $age_out_count; ls -f $output_dir"cli_record_"* 2>/dev/null) | sort | uniq -u | xargs -I {} rm -f -- {}
  (ls -f -t1 $output_dir"cli_timer_"* 2>/dev/null | head -n $age_out_count; ls -f $output_dir"cli_timer_"* 2>/dev/null) | sort | uniq -u | xargs -I {} rm -f -- {}

  exit 0
}

# Register the cleanup function to be called on the EXIT signal
trap cleanup EXIT INT QUIT TERM HUP

# Check if the script utility is installed and accessible
if ! command -v script &> /dev/null
then
    echo "The 'script' utility could not be found. Please install it and try again."
    exit 1
fi

# Generate a timestamp for unique filename
timestamp=$(date +%Y%m%d%H%M%S)
filename="cli_record_$timestamp"
ffilename="ctee_log_$timestamp"
tfilename="cli_timer_$timestamp"

# Create the target directory if it doesn't already exist
mkdir -p $output_dir

# Write the pid to a file and setup boilerplate components
echo $$ > $output_dir"ctee.pid"
output_cache_path=$output_dir"ctee_cache"
export CTEE_CURRENT_LOGFILE="$output_dir$filename"
CTEE_CMD_DELIMITER="--CTEE_CMD--"
export CTEE_CMD_DELIMITER="--CTEE_CMD--"
DB_FILE=$output_dir"cxwrite_notes.db"
export DB_FILE=$output_dir"cxwrite_notes.db"
CTEE_CURRENT_DBFILE="$output_dir$db_filename"
export CTEE_CURRENT_DBFILE="$output_dir$db_filename"

# Define a function to write note with the last run command
background_cxwrite() {
  local note=""
  local command_issued=""

  if [[ $# -eq 1 ]]; then
    note=$1
  elif [[ $# -ge 2 ]]; then
    echo "Error: Please provide at most one argument for the notes."
    return 1
  fi

  # Append history lines from this session to the history file
  history -a

  # Load history file
  history -r

  # Get the last command
  command_issued=$(history 1 | awk 'NR==1{$1=""; print substr($0,2)}')

  timestamp=$(date '+%Y-%m-%d %H:%M:%S')
  context=""  # The context field is always blank

  # Check if table 'notes' exists, if not create it
  sqlite3 $CTEE_CURRENT_DBFILE "CREATE TABLE IF NOT EXISTS notes (path STRING, timestamp STRING, command_issued STRING, context BLOB, note STRING);"

  # Insert the record into the notes table
  sqlite3 $CTEE_CURRENT_DBFILE "INSERT INTO notes (path, timestamp, command_issued, context, note) VALUES('$CTEE_CURRENT_LOGFILE', '$timestamp', '$command_issued', '', '$note');"
  echo $CTEE_CMD_DELIMITER
}

export -f background_cxwrite
PROMPT_COMMAND=background_cxwrite
export PROMPT_COMMAND=background_cxwrite

OS=$(uname -s)
if [ "$OS" = "Linux" ]
then
  # Check if the file exists
  bashrc_content_file=$HOME/.ctee/etc/bashrc.ctee
  if [[ -f "$bashrc_content_file" ]]; then
      # Create a temporary bashrc file
      temp_bashrc=$(mktemp)
      cat "$bashrc_content_file" >> "$temp_bashrc"
      echo 'export CTEE_CURRENT_LOGFILE="$CTEE_CURRENT_LOGFILE"' >> "$temp_bashrc"
  else
      echo "[!] Warning: '$bashrc_content_file' does not exist."
      echo "    - If not installed previously, run 'install.sh' and try again..."
      echo "    - If previously installed, run 'update.sh' script to attempt auto-fix..."
      exit 1

  fi
elif [ "$OS" = "Darwin" ]
then
  # macOS specific commands
  echo "[i] MacOS Version Enabled."
  if ! brew list | grep util-linux &>/dev/null; then
    brew install util-linux
  fi
else
  echo '[!] Ctee currently only operates on MacOS and Linux systems. Exiting...'
  exit 1
fi

# Start recording with the 'script' command
case $OS in
  Darwin)
    tfilename="NA_on_MacOS"
    script -q -t 0 -a "$output_dir$filename"
    echo ""
    echo "[+] CLI Recording File:"
    echo "$output_dir$filename"
    echo ""
    ;;
  Linux)
    script --timing="$output_dir$tfilename" -m advanced -eq -a "$output_dir$filename" --command="bash --rcfile $temp_bashrc"
    # Normalize the timing file of the resulting timing file
    cxtiming -f "$output_dir$tfilename" -n 2
    echo ""
    echo "[+] CLI Recording File : CLI Recording Timer File"
    echo "    $output_dir$filename:$output_dir$tfilename"
    echo ""
    ;;
  *)
    echo "[!] Ctee currently only operates on MacOS and Linux systems. Exiting..."
    exit 1
    ;;
esac

PROMPT_COMMAND=""
export PROMPT_COMMAND=""
echo "$CTEE_CURRENT_LOGFILE:$output_dir$tfilename" > "$output_cache_path"

# Remove any non-printable control sequences, simulate backspaces, and clear actions with no-ops
cxrmclear -f "$CTEE_CURRENT_LOGFILE"

# Write the stdout as a 'context' blob within the cxwrite_notes.db sqlite3 database for each command issued during sesion.
cxwrite "$CTEE_CURRENT_LOGFILE"

# Create a copy of the resulting logfile in the current working directory
# cp $CTEE_CURRENT_LOGFILE $starting_dir/$log_filename
cp $CTEE_CURRENT_DBFILE $starting_dir/$db_filename
